version: '3.8'

services:
  updater:
    build: .
    container_name: updater
    volumes:
      - ../:/base
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    env_file:
      - .env
    privileged: true
    restarts: always
    networks:
      - swag_facebooc

networks:
  swag_facebooc:
    external: true
